title: Vidhi Solanki Maru
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vidhism.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Vidhi Solanki Maru # add your name
author-img: vidhi_profile_pic.JPG # add your photo
about-author: I am RAN/BSS engineer having experience in commision, integration, migration of RAN elements. I like exploring and learning new technical things. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: vidhi244 # add your Github handle
social-linkedin: vidhi-maru-47542932 # add your Linkedin handle
social-email: # add your Email address

destination: ./build

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
