name: Jekyll Deploy

on: [push]

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: jekyll-deploy-gh-pages
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPO: ${{ secrets.REPO }}
          GITHUB_ACTOR: ${{ secrets.ACTOR }}
        uses: BryanSchuetz/jekyll-deploy-gh-pages@master
